### ISSUE TITLE
Incomplete Streaming of tweets

### ISSUE THREAD

**Issue by rakshitcr7** [twitter/hbc#181]
The problem I am facing is that while tweets are streaming, some of the tweets are left incomplete (the long tweets). 

For Example:
**Original Tweet:** "Another Silent revolution of Modi govt - Streets lights being replaced with LED bulbs, saving energy consumption & stopping toxic emissions."

**Tweet Shown :** "RT @BJP4India: Another Silent revolution of Modi govt - Streets lights being replaced with LED bulbs, saving energy consumption &…"

Not able to understand why its happening. This becomes a problem during sentiment analysing as it also considers "..." as a word.

**Comment by Jakob2014uafmx** [comment]
Hi,
I'm not affiliated to Twitter and/or the maintainers of this repo, but I faced the same problem as developer. The problem seems to be related to retweets, because in theory they might be longer than the usual 140 characters, as they also contain the `RT@<<user's screenName>>:` part in front of the original tweet, but in reality they seem to be truncated at the end to get a length <= 140 characters. I solved it by checking `isRetweet()` in the listener which processes the tweets and if yes, using 
`"RT @" + status.getRetweetedStatus().getUser().getScreenName() + ": " + status.getRetweetedStatus().getText()` instead of `status.getText()`

**Comment by cristobal-wetzig** [comment]
@Jakob2014uafmx  Thats a nice little hack!

Does anybody know how to actually add a parameter to the streamhandler so you send full_text for example?

**Comment by andypiper** [comment]
Extended Tweets in the Streaming API will contain an `extended_tweet` segment containing a `full_text` field.
